// Project Euler.net Problem 45
//
// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
//     Triangle      T(n) = n(n+1)/2     1, 3, 6, 10, 15, ...
//     Pentagonal    P(n) = n(3n-1)/2    1, 5, 12, 22, 35, ...
//     Hexagonal     H(n) = n(2n-1)      1, 6, 15, 28, 45, ...
// 
// It can be verified that T(285) = P(165) = H(143) = 40,755
// 
// Find the next triangle number that is also pentagonal and hexagonal.
//
// $Revision

#include <stdio.h>

//#define LIMIT 698576  // segfault with 698576, not with 698575
#define LIMIT 1600000000

int main()
{
    int nt, np, nh;
    int xt, xp, xh;
    int min, found;

    // Initialize
    nt = 1;  xt = nt*(nt+1)/2;
    np = 1;  xp = np*(3*np-1)/2;
    nh = 1;  xh = nh*(2*nh-1);

    // Increment nt, np, or nh until LIMIT or solution
    do {
        // Find which function(s) has the lowest result
        min = xt;
        if (xp < min)  min = xp;
        if (xh < min)  min = xh;

        if (min < 0)  {
            printf("Error: overflow\n");
            printf("    t(%d)=%d, p(%d)=%d, h(%d)=%d\n", nt, xt, np, xp, nh, xh);
            return (1);
        }

        // Step the function(s) with the lowest result
        //if (xt == min)  { nt++;  xt = nt*(nt+1)/2;   }
        //if (xp == min)  { np++;  xp = np*(3*np-1)/2; }
        //if (xh == min)  { nh++;  xh = nh*(2*nh-1);   }
        if (xt == min)  { nt++;  xt += nt;     }
        if (xp == min)  { np++;  xp += 3*np-2; }
        if (xh == min)  { nh++;  xh += 4*nh-3; }
        //if (xt == min)  { nt++;  xt += nt;      printf("t(%d)=%d\n", nt, xt); }
        //if (xp == min)  { np++;  xp += 3*np-2;  printf("p(%d)=%d\n", np, xp); }
        //if (xh == min)  { nh++;  xh += 4*nh-3;  printf("h(%d)=%d\n", nh, xh); }

        if ((xt == xp) && (xp == xh))
            printf("Solution found: t(%d)=%d, p(%d)=%d, h(%d)=%d\n", nt, xt, np, xp, nh, xh);
    } while ((xt < LIMIT) && (xp < LIMIT) && (xh < LIMIT));

    printf("Stopped searching at t(%d)=%d, p(%d)=%d h(%d)=%d\n", nt, xt, np, xp, nh, xh);
}
