// Project Euler.net Problem 44
//
// Pentagonal numbers are generated by the formula, P(n) = n(3n - 1)/2. The first ten
// pentagonal numbers are:
// 
//     1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
// 
// It can be seen that P(4) + P(7) = 22 + 70 = 92 = P(8). However, their difference,
// 70 - 22 = 48, is not pentagonal.
// 
// Find the pair of pentagonal numbers, P(j) and P(k), for which their sum and difference
// is pentagonal and D = |P(k) - P(j)| is minimised; what is the value of D?
// 
// $Revision

#include <stdio.h>

#define MAX 2500

int main()
{
    int p[MAX];
    int n;
    int j, k;

    // Generate a table of pentagonal numbers
    for (n = 1; n < MAX; n++) {
        p[n] = n * (3*n - 1) / 2;
        //printf("p[%d] = %d\n", n, p[n]);
    }

    int sum, diff;
    int sum_p, diff_p;
    for (j = 1; j < MAX; j++) {
        for (k = 1; k < j; k++) {
            sum  = p[j] + p[k];
            diff = p[j] - p[k];
            sum_p = 0;  diff_p = 0;
            for (n = 1; n < MAX; n++) {
                if (p[n] == sum)  sum_p = 1;
                if (p[n] == diff)  diff_p = 1;
            }
            if (sum_p && diff_p)
                printf("p[%d] = %d, p[%d] = %d, sum = %d, diff = %d\n", j, p[j], k, p[k], sum, diff);
        }
    }

    // Report answer
    printf("// Report answer\n");

}
