// Project Euler.net Problem 2
//
// Find the sum of all the even-valued terms in the Fibonacci sequence
// which do not exceed four million.
//
// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms
// will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// Find the sum of all the even-valued terms in the sequence which do
// not exceed four million.

#include <iostream>

int main ()
{
  const int LIMIT = 4000000;

  int f0 = 1;
  int f1 = 2;
  int n = 2;
  int answer = f1;

  while ((f0 + f1) < LIMIT) {
    n += 1;
    int temp = f0 + f1;
    f0 = f1;
    f1 = temp;

    if ((f1 % 2) == 0)
      answer += f1;  // f1 is even
  }

  std::cout << "The answer is " << answer << ".\n";
}
