// Project Euler.net Problem 2
//
// Find the sum of all the even-valued terms in the Fibonacci sequence
// which do not exceed four million.
//
// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms
// will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// Find the sum of all the even-valued terms in the sequence which do
// not exceed four million.

val size = 4000000
var f1, f0, temp = 1
var answer = 0
while (f1 < size) {
    temp = f1
    f1 = f0 + f1
    f0 = temp

    if (f1 % 2 == 0)
        answer += f1
    println(f1, answer)
}

println("Answer = " + answer)
//printf("Answer = %d\n", answer)  // Also works
