// Project Euler.net Problem 12
//
// The sequence of triangle numbers is generated by adding the natural
// numbers. So the 7^(th) triangle number would be 1 + 2 + 3 + 4 + 5 +
// 6 + 7 = 28. The first ten terms would be:
//
//     1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//
// Let us list the factors of the first seven triangle numbers:
//
//      1: 1
//      3: 1,3
//      6: 1,2,3,6
//     10: 1,2,5,10
//     15: 1,3,5,15
//     21: 1,3,7,21
//     28: 1,2,4,7,14,28
//
// We can see that 28 is the first triangle number to have over five divisors.
//
// What is the value of the first triangle number to have over five
// hundred divisors?

#include <stdio.h>

//#define MAX 80000000 
#define MAX 76576501
#define GOAL 500

int main()
{
    long i, j, k;
    int divs, record_divs = 0;

    // Try out triangle numbers
    printf("// Try out triangle numbers\n");
    long triangle = 0;
    for (i = 1; i < MAX; i++) {
        triangle += i;

        divs = 0;
        for (j = 1; j <= (1+triangle/2); j++) {
            if ((triangle % j) == 0) {
                divs++; 
            }
        }
        divs++;  // The number is also a divisor of itself

        if (divs > record_divs) {
            printf("%d: Triangle number %d has %d divisors\n", i, triangle, divs);
            record_divs = divs;

            printf("    ");
            for (j = 1; j <= MAX/2; j++) {
                if ((triangle % j) == 0) {
                    printf("%d ", j);
                }
            }
            printf("\n");

        }

        if (divs >= GOAL)  return(0);
        if (triangle >= MAX)  return(0);
    }

}
